In [1]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import seaborn as sns

In [ ]:
sns.set(style='whitegrid')

In [ ]:
df=pd.read_csv('types_of_cybercrime.csv')

In [ ]:
df.head(10)

,S. No,Crime Type,Category,2016,2017,2018,2019,2020,2021,Percentage Share,Avg Loss Lakhs,Risk Level
0,1,Phishing,Social Engineering,1450,1890,2340,2780,4120,4980,18.4,12.5,High
1,2,Online Banking Fraud,Financial,2100,2650,3100,3650,5200,6100,22.6,28.4,High
2,3,Identity Theft,Personal Data,780,920,1100,1350,1980,2450,9.1,8.2,Medium
3,4,Ransomware,Malware,120,210,340,480,890,1120,4.1,45.6,High
4,5,Hacking,Unauthorized Access,560,640,720,810,980,1150,4.3,15.8,High
5,6,Cyber Stalking,Personal Safety,430,510,650,740,860,1020,3.8,1.2,Medium
6,7,Credit Card Fraud,Financial,980,1210,1540,1780,2340,2760,10.2,9.7,High
7,8,Data Theft,Personal Data,310,380,450,530,710,890,3.3,22.1,High
8,9,Email Spoofing,Social Engineering,640,720,810,900,1050,1180,4.4,3.5,Low
9,10,Website Defacement,Unauthorized Access,190,210,240,260,300,340,1.3,2.1,Low

In [ ]:
df.tail(10)

,S. No,Crime Type,Category,2016,2017,2018,2019,2020,2021,Percentage Share,Avg Loss Lakhs,Risk Level
10,11,OTP Fraud,Financial,520,780,1120,1560,2450,3120,11.5,6.8,High
11,12,Social Media Abuse,Personal Safety,870,1020,1280,1490,1760,2010,7.4,0.8,Medium
12,13,ATM Skimming,Financial,210,180,160,140,110,90,0.3,4.2,Medium
13,14,Cryptocurrency Fraud,Financial,40,90,180,320,560,840,3.1,38.9,High
14,15,Fake Job Scam,Social Engineering,150,230,310,420,680,920,3.4,5.6,Medium
15,16,SIM Swap Fraud,Financial,80,140,220,310,470,650,2.4,11.3,High
16,17,Child Grooming Online,Personal Safety,90,110,130,150,180,210,0.8,0.0,High
17,18,Malware Distribution,Malware,260,300,350,400,480,540,2.0,7.4,Medium
18,19,Denial of Service,Unauthorized Access,70,90,110,130,160,190,0.7,18.2,Medium
19,20,Online Shopping Fraud,Financial,690,850,1040,1280,1890,2340,8.7,4.9,Medium

In [ ]:
print(df.shape)

(20, 12)

In [ ]:
print(df.columns)

Index(['S. No', 'Crime Type', 'Category', '2016', '2017', '2018', '2019',
       '2020', '2021', 'Percentage Share', 'Avg Loss Lakhs', 'Risk Level'],
      dtype='str')

In [ ]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   S. No             20 non-null     int64
 1   Crime Type        20 non-null     str
 2   Category          20 non-null     str
 3   2016              20 non-null     int64
 4   2017              20 non-null     int64
 5   2018              20 non-null     int64
 6   2019              20 non-null     int64
 7   2020              20 non-null     int64
 8   2021              20 non-null     int64
 9   Percentage Share  20 non-null     float64
 10  Avg Loss Lakhs    20 non-null     float64
 11  Risk Level        20 non-null     str
dtypes: float64(2), int64(7), str(3)
memory usage: 2.6 KB
None

In [ ]:
print(df.describe())

          S. No        2016         2017        2018         2019        2020  \
count  20.00000    20.00000    20.000000    20.00000    20.000000    20.00000
mean   10.50000   527.00000   656.500000   809.50000   974.000000  1358.50000
std     5.91608   525.15762   660.958435   790.15305   933.214027  1350.59938
min     1.00000    40.00000    90.000000   110.00000   130.000000   110.00000
25%     5.75000   142.50000   202.500000   235.00000   317.500000   477.50000
50%    10.50000   370.00000   445.000000   550.00000   635.000000   875.00000
75%    15.25000   712.50000   867.500000  1105.00000  1385.000000  1912.50000
max    20.00000  2100.00000  2650.000000  3100.00000  3650.000000  5200.00000

              2021  Percentage Share  Avg Loss Lakhs
count    20.000000         20.000000       20.000000
mean   1645.000000          6.090000       12.360000
std    1606.432792          5.942434       12.672075
min      90.000000          0.300000        0.000000
25%     622.500000          2.300000        4.025000
50%    1070.000000          3.950000        7.800000
75%    2367.500000          8.800000       16.400000
max    6100.000000         22.600000       45.600000

In [ ]:
print(df.describe(include='all'))

           S. No Crime Type   Category        2016         2017        2018  \
count   20.00000         20         20    20.00000    20.000000    20.00000
unique       NaN         20          6         NaN          NaN         NaN
top          NaN   Phishing  Financial         NaN          NaN         NaN
freq         NaN          1          7         NaN          NaN         NaN
mean    10.50000        NaN        NaN   527.00000   656.500000   809.50000
std      5.91608        NaN        NaN   525.15762   660.958435   790.15305
min      1.00000        NaN        NaN    40.00000    90.000000   110.00000
25%      5.75000        NaN        NaN   142.50000   202.500000   235.00000
50%     10.50000        NaN        NaN   370.00000   445.000000   550.00000
75%     15.25000        NaN        NaN   712.50000   867.500000  1105.00000
max     20.00000        NaN        NaN  2100.00000  2650.000000  3100.00000

               2019        2020         2021  Percentage Share  \
count     20.000000    20.00000    20.000000         20.000000
unique          NaN         NaN          NaN               NaN
top             NaN         NaN          NaN               NaN
freq            NaN         NaN          NaN               NaN
mean     974.000000  1358.50000  1645.000000          6.090000
std      933.214027  1350.59938  1606.432792          5.942434
min      130.000000   110.00000    90.000000          0.300000
25%      317.500000   477.50000   622.500000          2.300000
50%      635.000000   875.00000  1070.000000          3.950000
75%     1385.000000  1912.50000  2367.500000          8.800000
max     3650.000000  5200.00000  6100.000000         22.600000

        Avg Loss Lakhs Risk Level
count        20.000000         20
unique             NaN          3
top                NaN       High
freq               NaN         10
mean         12.360000        NaN
std          12.672075        NaN
min           0.000000        NaN
25%           4.025000        NaN
50%           7.800000        NaN
75%          16.400000        NaN
max          45.600000        NaN

In [ ]:
print("Missing values:\n", df.isnull().sum())

Missing values:
 S. No               0
Crime Type          0
Category            0
2016                0
2017                0
2018                0
2019                0
2020                0
2021                0
Percentage Share    0
Avg Loss Lakhs      0
Risk Level          0
dtype: int64

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
print(df.dtypes)

S. No                 int64
Crime Type              str
Category                str
2016                  int64
2017                  int64
2018                  int64
2019                  int64
2020                  int64
2021                  int64
Percentage Share    float64
Avg Loss Lakhs      float64
Risk Level              str
dtype: object

In [ ]:
print(df['Category'].value_counts())

Category
Financial              7
Social Engineering     3
Unauthorized Access    3
Personal Safety        3
Personal Data          2
Malware                2
Name: count, dtype: int64

In [ ]:
print(df['Risk Level'].value_counts())

Risk Level
High      10
Medium     8
Low        2
Name: count, dtype: int64

In [ ]:
plt.figure(figsize=(11,6))
sns.barplot(data=df.sort_values('2021', ascending=False), 
            x='Crime Type', y='2021', color='steelblue')
plt.xticks(rotation=75)
plt.title('Cases 2021 by Crime Type')
plt.tight_layout()
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\2611494479.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
a=df.groupby('Category')['2021'].sum().sort_values(ascending=False)
print(a)
plt.figure(figsize=(8,5))
sns.barplot(x=a.index, y=a.values, palette='Set2')
plt.xticks(rotation=20)
plt.title('2021 Cases by Category')
plt.show()

Category
Financial              15900
Social Engineering      7080
Personal Data           3340
Personal Safety         3240
Unauthorized Access     1680
Malware                 1660
Name: 2021, dtype: int64

C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\3212715496.py:4: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(x=a.index, y=a.values, palette='Set2')
C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\3212715496.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
plt.figure(figsize=(7,7))
plt.pie(a, labels=a.index, autopct='%1.1f%%')
plt.title('Category Share 2021')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\2280590824.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [22]:
y=df[['2016','2017','2018','2019','2020','2021']].sum()
print(y)
plt.figure(figsize=(8,4))
plt.plot(y.index, y.values, marker='o', color='darkred')
plt.title('Total Cases 2016 to 2021')
plt.ylabel('Cases')
plt.show()

2016    10540
2017    13130
2018    16190
2019    19480
2020    27170
2021    32900
dtype: int64

C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\288776478.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [23]:
m=df.melt(id_vars=['Crime Type','Category'], value_vars=['2016','2017','2018','2019','2020','2021'], var_name='Year', value_name='Cases')
plt.figure(figsize=(9,5))
sns.lineplot(data=m, x='Year', y='Cases', hue='Category', marker='o', estimator=np.sum)
plt.title('Cases by Category Over Years')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\1240505208.py:5: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [24]:
plt.figure(figsize=(6,4))
sns.countplot(x='Risk Level', data=df, palette='Reds', order=['Low','Medium','High'])
plt.title('Risk Level Count')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\1122432208.py:2: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.countplot(x='Risk Level', data=df, palette='Reds', order=['Low','Medium','High'])
C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\1122432208.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [25]:
plt.figure(figsize=(9,5))
sns.barplot(data=df, x='Category', y='Avg Loss Lakhs', hue='Risk Level')
plt.xticks(rotation=20)
plt.title('Average Loss by Category')
plt.tight_layout()
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\1773371672.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [26]:
plt.figure(figsize=(8,6))
sns.scatterplot(data=df, x='2021', y='Avg Loss Lakhs', hue='Category', size='Percentage Share')
plt.title('Cases vs Loss')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\2989951250.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [27]:
plt.figure(figsize=(8,6))
sns.boxplot(x='Risk Level', y='Avg Loss Lakhs', data=df, palette='pastel', order=['Low','Medium','High'])
plt.title('Loss by Risk')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\833560262.py:2: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.boxplot(x='Risk Level', y='Avg Loss Lakhs', data=df, palette='pastel', order=['Low','Medium','High'])
C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\833560262.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [28]:
h=df.set_index('Crime Type')[['2016','2017','2018','2019','2020','2021']]
plt.figure(figsize=(8,10))
sns.heatmap(h, cmap='YlGnBu')
plt.title('Crime Type by Year')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\994207877.py:5: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [29]:
plt.figure(figsize=(7,5))
sns.heatmap(df[['2016','2017','2018','2019','2020','2021','Percentage Share','Avg Loss Lakhs']].corr(), annot=True, cmap='coolwarm', center=0)
plt.title('Correlation')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\2181082270.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [30]:
t=df.sort_values('Percentage Share', ascending=False).head(8)
print(t[['Crime Type','Percentage Share','Risk Level']])
plt.figure(figsize=(9,5))
sns.barplot(data=t, x='Crime Type', y='Percentage Share', hue='Risk Level')
plt.xticks(rotation=45)
plt.title('Top Crime Share')
plt.tight_layout()
plt.show()

               Crime Type  Percentage Share Risk Level
1    Online Banking Fraud              22.6       High
0                Phishing              18.4       High
10              OTP Fraud              11.5       High
6       Credit Card Fraud              10.2       High
2          Identity Theft               9.1     Medium
19  Online Shopping Fraud               8.7     Medium
11     Social Media Abuse               7.4     Medium
8          Email Spoofing               4.4        Low

C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\3101196857.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [31]:
plt.figure(figsize=(8,4))
sns.histplot(df['2021'], bins=8, kde=True, color='teal')
plt.title('2021 Cases Distribution')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_26092\2293478289.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [32]:
print(df.groupby('Category')[['2016','2021','Avg Loss Lakhs']].mean())

                           2016         2021  Avg Loss Lakhs
Category
Financial            660.000000  2271.428571       14.885714
Malware              190.000000   830.000000       26.500000
Personal Data        545.000000  1670.000000       15.150000
Personal Safety      463.333333  1080.000000        0.666667
Social Engineering   746.666667  2360.000000        7.200000
Unauthorized Access  273.333333   560.000000       12.033333

In [33]:
print(df.sort_values('Avg Loss Lakhs', ascending=False)[['Crime Type','Avg Loss Lakhs']].head())

              Crime Type  Avg Loss Lakhs
3             Ransomware            45.6
13  Cryptocurrency Fraud            38.9
1   Online Banking Fraud            28.4
7             Data Theft            22.1
18     Denial of Service            18.2

In [34]:
print('Done')

Done