In [ ]:
import numpy as np

:

In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import seaborn as sns

In [ ]:
sns.set(style='whitegrid')

In [ ]:
df=pd.read_csv('cyber_crimes.csv', sep='\t')

In [ ]:
df.head(10)

,S. No,Category,State/UT,2016,2017,2018,Percentage Share of State/UT (2018),Mid-Year Projected Population (in Lakhs) (2018)+,Rate of Total Cyber Crimes (2018)++
0,1,State,Andhra Pradesh,616,931,1207,4.4,520.3,2.3
1,2,State,Arunachal Pradesh,4,1,7,0.0,14.9,0.5
2,3,State,Assam,696,1120,2022,7.4,340.4,5.9
3,4,State,Bihar,309,433,374,1.4,1183.3,0.3
4,5,State,Chhattisgarh,90,171,139,0.5,284.7,0.5
5,6,State,Goa,31,13,29,0.1,15.3,1.9
6,7,State,Gujarat,362,458,702,2.6,673.2,1.0
7,8,State,Haryana,401,504,418,1.5,284.0,1.5
8,9,State,Himachal Pradesh,31,56,69,0.3,72.7,0.9
9,10,State,Jammu & Kashmir,28,63,73,0.3,134.3,0.5

In [ ]:
df.tail(10)

,S. No,Category,State/UT,2016,2017,2018,Percentage Share of State/UT (2018),Mid-Year Projected Population (in Lakhs) (2018)+,Rate of Total Cyber Crimes (2018)++
29,State,State,Total State(s),12187,21593,27004,99.1,12997.9,2.1
30,30,Union Territory,A & N Islands,3,3,7,0.0,4.0,1.8
31,31,Union Territory,Chandigarh,26,32,30,0.1,11.7,2.6
32,32,Union Territory,D&N Haveli,1,1,0,0.0,5.3,0.0
33,33,Union Territory,Daman & Diu,0,0,0,0.0,4.0,0.0
34,34,Union Territory,Delhi UT,98,162,189,0.7,195.6,1.0
35,35,Union Territory,Lakshadweep,0,0,4,0.0,0.7,6.0
36,36,Union Territory,Puducherry,2,5,14,0.1,14.8,0.9
37,Union Territory,Union Territory,Total UT(s),130,203,244,0.9,236.0,1.0
38,Total (All India),Total (All India),Total (All India),12317,21796,27248,100.0,13233.8,2.1

In [ ]:
print(df.shape)

(39, 9)

In [ ]:
print(df.columns)

Index(['S. No', 'Category', 'State/UT', '2016', '2017', '2018',
       'Percentage Share of State/UT (2018)',
       'Mid-Year Projected Population (in Lakhs) (2018)+',
       'Rate of Total Cyber Crimes (2018)++'],
      dtype='str')

In [ ]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 9 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   S. No                                             39 non-null     str
 1   Category                                          39 non-null     str
 2   State/UT                                          39 non-null     str
 3   2016                                              39 non-null     int64
 4   2017                                              39 non-null     int64
 5   2018                                              39 non-null     int64
 6   Percentage Share of State/UT (2018)               39 non-null     float64
 7   Mid-Year Projected Population (in Lakhs) (2018)+  39 non-null     float64
 8   Rate of Total Cyber Crimes (2018)++               39 non-null     float64
dtypes: float64(3), int64(3), str(3)
memory usage: 3.6 KB
None

In [ ]:
print(df.describe())

               2016          2017          2018  \
count     39.000000     39.000000     39.000000
mean     947.461538   1676.615385   2096.000000
std     2724.974532   4832.658115   6065.161416
min        0.000000      0.000000      0.000000
25%        9.500000     11.500000     24.500000
50%      102.000000    176.000000    239.000000
75%      439.500000    772.000000    886.500000
max    12317.000000  21796.000000  27248.000000

       Percentage Share of State/UT (2018)  \
count                            39.000000
mean                              7.689744
std                              22.257391
min                               0.000000
25%                               0.100000
50%                               0.900000
75%                               3.250000
max                             100.000000

       Mid-Year Projected Population (in Lakhs) (2018)+  \
count                                         39.000000
mean                                        1017.987179
std                                         2885.991893
min                                            0.700000
25%                                           18.300000
50%                                          284.000000
75%                                          663.850000
max                                        13233.800000

       Rate of Total Cyber Crimes (2018)++
count                            39.000000
mean                              1.689744
std                               1.811193
min                               0.000000
25%                               0.500000
50%                               1.000000
75%                               2.200000
max                               8.900000

In [ ]:
print(df.describe(include='all'))

       S. No Category        State/UT          2016          2017  \
count     39       39              39     39.000000     39.000000
unique    39        3              39           NaN           NaN
top        1    State  Andhra Pradesh           NaN           NaN
freq       1       30               1           NaN           NaN
mean     NaN      NaN             NaN    947.461538   1676.615385
std      NaN      NaN             NaN   2724.974532   4832.658115
min      NaN      NaN             NaN      0.000000      0.000000
25%      NaN      NaN             NaN      9.500000     11.500000
50%      NaN      NaN             NaN    102.000000    176.000000
75%      NaN      NaN             NaN    439.500000    772.000000
max      NaN      NaN             NaN  12317.000000  21796.000000

                2018  Percentage Share of State/UT (2018)  \
count      39.000000                            39.000000
unique           NaN                                  NaN
top              NaN                                  NaN
freq             NaN                                  NaN
mean     2096.000000                             7.689744
std      6065.161416                            22.257391
min         0.000000                             0.000000
25%        24.500000                             0.100000
50%       239.000000                             0.900000
75%       886.500000                             3.250000
max     27248.000000                           100.000000

        Mid-Year Projected Population (in Lakhs) (2018)+  \
count                                          39.000000
unique                                               NaN
top                                                  NaN
freq                                                 NaN
mean                                         1017.987179
std                                          2885.991893
min                                             0.700000
25%                                            18.300000
50%                                           284.000000
75%                                           663.850000
max                                         13233.800000

        Rate of Total Cyber Crimes (2018)++
count                             39.000000
unique                                  NaN
top                                     NaN
freq                                    NaN
mean                               1.689744
std                                1.811193
min                                0.000000
25%                                0.500000
50%                                1.000000
75%                                2.200000
max                                8.900000

In [ ]:
print("Missing values:\n", df.isnull().sum())

Missing values:
 S. No                                               0
Category                                            0
State/UT                                            0
2016                                                0
2017                                                0
2018                                                0
Percentage Share of State/UT (2018)                 0
Mid-Year Projected Population (in Lakhs) (2018)+    0
Rate of Total Cyber Crimes (2018)++                 0
dtype: int64

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
print(df.dtypes)

S. No                                                   str
Category                                                str
State/UT                                                str
2016                                                  int64
2017                                                  int64
2018                                                  int64
Percentage Share of State/UT (2018)                 float64
Mid-Year Projected Population (in Lakhs) (2018)+    float64
Rate of Total Cyber Crimes (2018)++                 float64
dtype: object

In [ ]:
df.columns=['SNo','Category','State','Y2016','Y2017','Y2018','Share2018','Population','Rate2018']

In [ ]:
df.head()

,SNo,Category,State,Y2016,Y2017,Y2018,Share2018,Population,Rate2018
0,1,State,Andhra Pradesh,616,931,1207,4.4,520.3,2.3
1,2,State,Arunachal Pradesh,4,1,7,0.0,14.9,0.5
2,3,State,Assam,696,1120,2022,7.4,340.4,5.9
3,4,State,Bihar,309,433,374,1.4,1183.3,0.3
4,5,State,Chhattisgarh,90,171,139,0.5,284.7,0.5

In [ ]:
print(df['Category'].value_counts())

Category
State                30
Union Territory       8
Total (All India)     1
Name: count, dtype: int64

In [ ]:
d=df[~df['State'].str.contains('Total', case=False)]
print(d.shape)
d.head()

(36, 9)

,SNo,Category,State,Y2016,Y2017,Y2018,Share2018,Population,Rate2018
0,1,State,Andhra Pradesh,616,931,1207,4.4,520.3,2.3
1,2,State,Arunachal Pradesh,4,1,7,0.0,14.9,0.5
2,3,State,Assam,696,1120,2022,7.4,340.4,5.9
3,4,State,Bihar,309,433,374,1.4,1183.3,0.3
4,5,State,Chhattisgarh,90,171,139,0.5,284.7,0.5

In [ ]:
print(d[['Y2016','Y2017','Y2018']].sum())

Y2016    12317
Y2017    21796
Y2018    27248
dtype: int64

In [ ]:
y=d[['Y2016','Y2017','Y2018']].sum()
print(y)
plt.figure(figsize=(7,4))
sns.barplot(x=y.index, y=y.values, palette='Blues')
plt.title('Total Cases by Year')
plt.ylabel('Cases')
plt.show()

Y2016    12317
Y2017    21796
Y2018    27248
dtype: int64

C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\1221928872.py:4: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(x=y.index, y=y.values, palette='Blues')
C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\1221928872.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
plt.figure(figsize=(7,4))
plt.plot(['2016','2017','2018'], y.values, marker='o', color='red')
plt.title('Cases Over Years')
plt.ylabel('Cases')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\4000595419.py:5: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
plt.figure(figsize=(6,4))
sns.countplot(x='Category', data=d, palette='Set2')
plt.title('State and UT Count')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\852993901.py:2: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.countplot(x='Category', data=d, palette='Set2')
C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\852993901.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
k=d.groupby('Category')[['Y2016','Y2017','Y2018']].sum()
print(k)
k.plot(kind='bar', figsize=(8,5))
plt.title('Cases State vs UT')
plt.tight_layout()
plt.show()

                 Y2016  Y2017  Y2018
Category
State            12187  21593  27004
Union Territory    130    203    244

C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\1305043725.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
t=d.sort_values('Y2018', ascending=False).head(10)
print(t[['State','Y2018']])
plt.figure(figsize=(10,5))
sns.barplot(data=t, x='State', y='Y2018', color='teal')
plt.xticks(rotation=45)
plt.title('Top 10 States 2018')
plt.tight_layout()
plt.show()

             State  Y2018
26   Uttar Pradesh   6280
11       Karnataka   5839
14     Maharashtra   3511
2            Assam   2022
0   Andhra Pradesh   1207
24       Telangana   1205
21       Rajasthan   1104
10       Jharkhand    930
19          Odisha    843
13  Madhya Pradesh    740

C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\3369079939.py:8: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
t2=d.sort_values('Y2018').head(10)
plt.figure(figsize=(10,5))
sns.barplot(data=t2, x='State', y='Y2018', color='grey')
plt.xticks(rotation=45)
plt.title('Lowest 10 States 2018')
plt.tight_layout()
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\844069095.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
plt.figure(figsize=(10,6))
sns.barplot(data=d.sort_values('Share2018', ascending=False).head(12), x='Share2018', y='State', color='purple')
plt.title('Share 2018')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\3862987570.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
plt.figure(figsize=(10,6))
sns.barplot(data=d.sort_values('Rate2018', ascending=False).head(12), x='Rate2018', y='State', color='orange')
plt.title('Crime Rate 2018')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\684663591.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
plt.figure(figsize=(8,6))
sns.scatterplot(data=d, x='Population', y='Y2018', hue='Category', size='Rate2018')
plt.title('Population vs Cases 2018')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\4191252904.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
plt.figure(figsize=(8,6))
sns.scatterplot(data=d, x='Y2017', y='Y2018', hue='Category')
plt.title('2017 vs 2018 Cases')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\1924524696.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
h=d.set_index('State')[['Y2016','Y2017','Y2018']].head(15)
plt.figure(figsize=(8,8))
sns.heatmap(h, annot=True, fmt='.0f', cmap='YlOrRd')
plt.title('Cases Heatmap')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\1427549960.py:5: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
plt.figure(figsize=(6,5))
sns.heatmap(d[['Y2016','Y2017','Y2018','Share2018','Population','Rate2018']].corr(), annot=True, cmap='coolwarm', center=0)
plt.title('Correlation')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\3281317907.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
plt.figure(figsize=(8,4))
sns.boxplot(data=d[['Y2016','Y2017','Y2018']])
plt.title('Year Case Spread')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\513862955.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
plt.figure(figsize=(8,4))
sns.histplot(d['Y2018'], bins=12, kde=True, color='green')
plt.title('2018 Cases Distribution')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\329919703.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
m=d.melt(id_vars=['State','Category'], value_vars=['Y2016','Y2017','Y2018'], var_name='Year', value_name='Cases')
plt.figure(figsize=(8,5))
sns.boxplot(data=m, x='Year', y='Cases', hue='Category')
plt.title('Cases by Year and Category')
plt.show()

C:\Users\harsh\AppData\Local\Temp\ipykernel_34052\1440812689.py:5: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [ ]:
print(d.sort_values('Y2018', ascending=False)[['State','Y2016','Y2017','Y2018','Rate2018']].head(8))

             State  Y2016  Y2017  Y2018  Rate2018
26   Uttar Pradesh   2639   4971   6280       2.8
11       Karnataka   1101   3174   5839       8.9
14     Maharashtra   2380   3604   3511       2.9
2            Assam    696   1120   2022       5.9
0   Andhra Pradesh    616    931   1207       2.3
24       Telangana    593   1209   1205       3.3
21       Rajasthan    941   1304   1104       1.4
10       Jharkhand    259    720    930       2.5

In [ ]:
print('Done')

Done